"""Initial migration

Revision ID: 0ee63a2f25a2
Revises: 12ceb9e09860
Create Date: 2024-11-26 10:17:43.153326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ee63a2f25a2'
down_revision = '12ceb9e09860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
