"""Update registration and 2factor

Revision ID: 36eb097234a6
Revises: 0ee63a2f25a2
Create Date: 2024-11-26 11:16:19.724609

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36eb097234a6'
down_revision = '0ee63a2f25a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('failed_otp_attempts', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lockout_until')
    op.drop_column('user', 'failed_otp_attempts')
    op.drop_column('user', 'otp_secret')
    # ### end Alembic commands ###
